### ISSUE TITLE
robots noarchive

### ISSUE THREAD

**Issue by BigfishDev** [zachakbar/boilerplate#3]
<meta name="robots" content="noarchive" />

Should we be using this in the boilerplate? 
https://www.searchenginejournal.com/when-why-and-how-to-use-noarchive/7422/

**Comment by zachakbar** [comment]
Good find, it looks like the pros/cons for adding that depend on the type of site you are building. I am going to assume that most of our customers would appreciate google indexing their site, so leaving it out sounds like the best plan. We have it here if we need it. :)
